language: android
jdk: oraclejdk8
sudo: required
dist: trusty
group: edge

env:
  global:
    - API=22
    - ANDROID_HOME=/usr/local/android-sdk-23.0.1
    - TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
    - ADB_INSTALL_TIMEOUT=20
    - BROWSERSTACK_UPLOAD=https://api.browserstack.com/app-automate/upload
    - BENCHMARK_APK="android/app/build/outputs/apk/app-benchmark-debug.apk"

android:
  components:
    - build-tools-23.0.1
    - android-23

before_install:
  # Install node.js
  - nvm install 8
  - node --version

install:
  # Install Android dependencies
  - sdkmanager --list || true  - sdkmanager --uninstall "system-images;android-15;default;armeabi-v7a"
  - sdkmanager --uninstall "extras;google;google_play_services"
  - echo yes | sdkmanager "tools" > /dev/null
  - echo yes | sdkmanager "platforms;android-${API}" > /dev/null
  - echo yes | sdkmanager "extras;android;m2repository" > /dev/null
  - echo yes | sdkmanager "extras;google;m2repository" > /dev/null
  - sdkmanager --list || true
  - sudo ln -s /usr/local/android-sdk-25.2.3 /usr/local/android-sdk-23.0.1
  # Install the React Native project dependencies
  - npm install -g yarn
  - cd "$TRAVIS_BUILD_DIR" && yarn

script:
  # Build the background Node.js process containing only tests
  - ./build-rnnodeapp.sh benchmark
  # Build the React Native Android app for benchmarking
  - cd android && ./gradlew clean && ./gradlew assembleBenchmarkDebug && cd ..
  # Upload to BrowserStack
  - export BROWSERSTACK_APP_URL=$(curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" -X POST "$BROWSERSTACK_UPLOAD" -F "file=@/$TRAVIS_BUILD_DIR/$BENCHMARK_APK" | cut -c 13-57)
  # Run automated test that verifies the benchmark results
  - node ./benchmark/test.js ci;
